logging.level.root=INFO
logging.level.com.aishu.wf.api=DEBUG
spring.main.banner-mode = console
mybatis-plus.global-config.banner=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

server.dbtype=mysql
server.rds-host=mariadb-mariadb-master.resource
server.rds-port=3330
server.rds-database=workflow
spring.datasource.username=anyshare
spring.datasource.password=eisoo.com123
spring.datasource.connectionTimeout=60000
spring.datasource.idleTimeout=600000
spring.datasource.validationTimeout=3000
spring.datasource.maxLifetime=700000
spring.datasource.maximumPoolSize=10
spring.datasource.validationQuery=select 1 from dual

server.port=8081
server.additionalPorts=8083
server.servlet.context-path=/api/workflow-rest
spring.aop.auto=true
server.compression.enabled=true
server.compression.min-response-size=1
server.tomcat.connection-timeout=5000
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-http-form-post-size=5MB
server.tomcat.max-swallow-size=5MB
server.max-http-header-size=32KB
server.tomcat.max-http-response-header-size=32KB

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.servlet.session.timeout=PT4H
spring.main.allow-circular-references=true

# mybatis-plus
mybatis-plus.type-aliases-package=com.**.dao
mybatis-plus.mapper-locations=classpath*:mapping/**/*Mapper.xml

# Redis
redis.connectType=sentinel
# Redis集群配置
redis.cluster.host=192.168.1.168
redis.cluster.port=6379
redis.cluster.username=
redis.cluster.password=123456
# Redis��������
redis.standalone.host=192.168.1.168
redis.standalone.port=6379
redis.standalone.username=
redis.standalone.password=123456
# Redis����ģʽ����
redis.masterSlave.masterHost=
redis.masterSlave.masterPort=6379
redis.masterSlave.slaveHost=
redis.masterSlave.slavePort=6379
redis.masterSlave.username=
redis.masterSlave.password=
# Redis�ڱ�ģʽ����
redis.sentinel.sentinelHost=proton-redis-proton-redis-sentinel.resource
redis.sentinel.sentinelPort=26379
redis.sentinel.masterGroupName=mymaster
redis.sentinel.username=root
redis.sentinel.password=eisoo.com123
redis.sentinel.sentinelUsername=root
redis.sentinel.sentinelPassword=eisoo.com123
# Redis SSL��֤����
redis.enableSSL=false
redis.secretName=
redis.caName=
redis.certName=
redis.keyName=

#nsq
nsq.type=kafka
nsq.produce-host=kafka-headless.resource.svc.cluster.local
nsq.produce-port=9097
nsq.lookup-host=
nsq.lookup-port=
nsq.lookup.httpurl=http://proton-mq-nsq-nsqlookupd.resource.svc.cluster.local:4161
nsq.auth.username=anyrobot
nsq.auth.password=eisoo.com123
nsq.auth.mechanism=PLAIN

anyshare.hydra-admin-point=http://hydra-admin.anyshare:4445/admin
anyshare.user-management-point=http://user-management-private.anyshare:30980
anyshare.docshare-public-point=http://doc-share-public.anyshare:30920
anyshare.eacp-point=http://eacp-private.anyshare:9998
anyshare.efast-point=http://efast-private.anyshare:9123
anyshare.docset-point=http://docset-private.anyshare:32597
anyshare.language=zh_CN.UTF-8
anyshare.deploy-service-point=http://deploy-service.anyshare:9703
anyshare.document-point=http://document-private:30920
#knife4j
knife4j.enable=true
knife4j.production=false
#Actuator
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=/actuator/health
# thrift
thrift.eacphost=192.168.1.202
thrift.eacplogPort=9993
thrift.evfshost=192.168.1.202
thrift.evfsPort=9064
thrift.sharemgnthost=sharemgnt.anyshare.svc.cluster.local
thrift.sharemgntPort=9600
# custom
my.shareAuditorFilteringInitiatedBySelf=true
my.auditorFilteringInitiatedBySelf=true
ut.disable-aspect=false

# execute_db_actuator=true
execute_workflow_config_init=false
module.version=

# 禁用swagger
springfox.documentation.enabled=false
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false