logging.level.root=ERROR
logging.level.com.aishu.wf.api=ERROR
spring.main.banner-mode = console
mybatis-plus.global-config.banner=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

server.dbtype=mysql
server.rds-host=10.97.115.118
server.rds-port=3330
server.rds-database=workflow
spring.datasource.username=workflow
spring.datasource.password=wwwwww
spring.datasource.connectionTimeout=60000
spring.datasource.idleTimeout=600000
spring.datasource.validationTimeout=3000
spring.datasource.maxLifetime=700000
spring.datasource.maximumPoolSize=50
spring.datasource.validationQuery=select 1 from dual

server.port=8081
server.servlet.context-path=/api/workflow-rest
spring.aop.auto=true
server.compression.enabled=true
server.compression.min-response-size=1
server.tomcat.connection-timeout=5000
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-http-form-post-size=5MB
server.tomcat.max-swallow-size=5MB
server.max-http-header-size=32KB
server.tomcat.max-http-response-header-size=32KB

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.servlet.session.timeout=PT4H

# Redis
redis.connectType=
# Redis集群配置
redis.cluster.host=192.168.1.168
redis.cluster.port=6379
redis.cluster.username=
redis.cluster.password=123456
# Redis��������
redis.standalone.host=192.168.1.168
redis.standalone.port=6379
redis.standalone.username=
redis.standalone.password=123456
# Redis����ģʽ����
redis.masterSlave.masterHost=
redis.masterSlave.masterPort=6379
redis.masterSlave.slaveHost=
redis.masterSlave.slavePort=6379
redis.masterSlave.username=
redis.masterSlave.password=
# Redis�ڱ�ģʽ����
redis.sentinel.sentinelHost=
redis.sentinel.sentinelPort=6379
redis.sentinel.masterGroupName=
redis.sentinel.username=
redis.sentinel.password=
redis.sentinel.sentinelUsername=
redis.sentinel.sentinelPassword=
# Redis SSL��֤����
redis.enableSSL=false
redis.secretName=
redis.caName=
redis.certName=
redis.keyName=

# mybatis-plus
mybatis-plus.type-aliases-package=com.**.dao
mybatis-plus.mapper-locations=classpath*:mapping/**/*Mapper.xml

#nsq
nsq.type=nsq
nsq.produce-host=192.168.1.168
nsq.produce-port=4150
nsq.lookup-host=192.168.1.168
nsq.lookup-port=4161

anyshare.hydra-admin-point=http://192.168.1.199:9080
anyshare.user-management-point=http://192.168.1.199:9080
anyshare.docshare-public-point=http://192.168.1.199:9080
anyshare.eacp-point=http://192.168.1.199:9080
anyshare.efast-point=http://192.168.1.199:9080
anyshare.docset-point=http://192.168.1.199:9080
# knife4j
knife4j.enable=true
knife4j.production=false
# Actuator
management.endpoint.health.show-details=always
# thrift
thrift.eacphost=192.168.1.199
thrift.eacplogPort=9993
thrift.evfshost=192.168.1.199
thrift.evfsPort=9064
# custom
my.shareAuditorFilteringInitiatedBySelf=true
my.auditorFilteringInitiatedBySelf=true
# execute_db_actuator=true
execute_workflow_config_init=false