apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name}}
  namespace: {{ .Values.namespace}}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/app-root: /dip-hub
spec:
  ingressClassName: {{ index .Values.depServices "class-443" "ingressClass" }}
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: {{.Values.service.port}}
        path: /api/dip-hub
        pathType: ImplementationSpecific
      - backend:
          service:
            name: {{.Values.service.name}}
            port:
              number: {{.Values.service.port}}
        path: /api/dip
        pathType: ImplementationSpecific
