/*
 * 文档访问
 * API to access AnyShare    如有任何疑问，可到开发者社区提问：https://developers.aishu.cn  # Authentication  - 调用需要鉴权的API，必须将token放在HTTP header中：\"Authorization: Bearer ACCESS_TOKEN\"  - 对于GET请求，除了将token放在HTTP header中，也可以将token放在URL query string中：\"tokenid=ACCESS_TOKEN\"
 *
 * OpenAPI spec version: 7.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aishu.wf.core.anyshare.client;

import com.aishu.wf.core.anyshare.config.AnyShareConfig;
import lombok.extern.slf4j.Slf4j;
import okhttp3.*;

import java.io.IOException;
import java.util.Arrays;

/**
 * @description 爱数接口调用客户端
 * @author hanj
 */
@Slf4j
public class AnyShareClient {

	AnyShareConfig anyShareConfig;
	ApiClient userManagementApiClient;
	ApiClient eacpApiClient;
	ApiClient hydraAdminPoint;
	ApiClient efastApiClient;
	ApiClient docsetApiClient;
	ApiClient deployServiceApiClient;
	ApiClient documentApiClient;
	ApiClient appstoreApiClient;
	ApiClient docsharePublicClient;
	ApiClient personalConfigPrivateClient;
	ApiClient docsharePrivateClient;
	ApiClient messageApiClient;

	public AnyShareClient(AnyShareConfig anyShareConfig) {
		this.anyShareConfig = anyShareConfig;
		OkHttpClient httpClient = new OkHttpClient.Builder()
				.addInterceptor(new OAuth2Interceptor())
				.connectionSpecs(Arrays.asList(ConnectionSpec.MODERN_TLS, ConnectionSpec.COMPATIBLE_TLS, ConnectionSpec.CLEARTEXT))
				.sslSocketFactory(TrustAll.socketFactory(), new TrustAll.trustManager())
				.hostnameVerifier(new TrustAll.hostnameVerifier())
				.build();
		userManagementApiClient = new ApiClient(httpClient, anyShareConfig.getUserManagementPoint());
		eacpApiClient = new ApiClient(httpClient, anyShareConfig.getEacpPoint());
		docsharePublicClient = new ApiClient(httpClient, anyShareConfig.getDocsharePublicPoint());
		hydraAdminPoint = new ApiClient(httpClient, anyShareConfig.getHydraAdminPoint());
		efastApiClient = new ApiClient(httpClient, anyShareConfig.getEfastPoint());
		docsetApiClient = new ApiClient(httpClient, anyShareConfig.getDocsetPoint());
		deployServiceApiClient = new ApiClient(httpClient, anyShareConfig.getDeployServicePoint());
		documentApiClient = new ApiClient(httpClient, anyShareConfig.getDocumentPoint());
		appstoreApiClient = new ApiClient(httpClient, anyShareConfig.getAppstorePoint());
		personalConfigPrivateClient = new ApiClient(httpClient, anyShareConfig.getPersonalConfigPoint());
		docsharePrivateClient = new ApiClient(httpClient,anyShareConfig.getDocsharePrivatePoint());
		messageApiClient = new ApiClient(httpClient, anyShareConfig.getMessagePrivatePoint());
	}

	class OAuth2Interceptor implements Interceptor {
		@Override
		public Response intercept(Interceptor.Chain chain) throws IOException {
			Request request = chain.request();
			long t1 = System.currentTimeMillis();
			if (log.isDebugEnabled()) {
				log.debug(String.format("Sending request %s", request.url()));
			}
			Response response = chain.proceed(request);
			if (log.isDebugEnabled()) {
				long t2 = System.currentTimeMillis();
				log.debug(String.format("Received response for %s in %dms%n%s", response.request().url(),
						t2 - t1, response.headers()));
			}
			return response;
		}
	}

	/**
	 * @description Hydra
	 * @author ouandyang
	 * @param
	 * @updateTime 2021/5/13
	 */
	public UserManagementOperation getHydraApi() {
		return new UserManagementOperation(hydraAdminPoint);
	}

	/**
	 * @description 用户管理
	 * @author hanj
	 * @param
	 * @updateTime 2021/5/13
	 */
	public UserManagementOperation getUserManagementOperation() {
		return new UserManagementOperation(userManagementApiClient);
	}

	/**
	 * @description 流程消息管理
	 * @author hanj
	 * @param
	 * @updateTime 2021/5/13
	 */
	public ProcessMessageOperation getProcessMessageOperation() {
		return new ProcessMessageOperation(eacpApiClient, messageApiClient);
	}

	/**
	 * @description 部门管理
	 * @author hanj
	 * @param
	 * @updateTime 2021/5/13
	 */
	public DepartmentApi getDepartmentApi(){
		return new DepartmentApi(userManagementApiClient);
	}

	/**
	 * @description efast内部api
	 * @author hanj
	 * @param
	 * @updateTime 2021/5/13
	 */
	public EfastApi getEfastApi(){
		return new EfastApi(efastApiClient);
	}

	/**
	 * @description docset内部api
	 * @author hanj
	 * @param
	 * @updateTime 2021/5/13
	 */
	public DocsetApi getDocsetApi(){
		return new DocsetApi(docsetApiClient);
	}

	/**
	 * @description deployService内部api
	 * @author ouandyang
	 * @param
	 * @updateTime 2021/5/13
	 */
	public DeployServiceApi getDeployServiceApi(){
		return new DeployServiceApi(deployServiceApiClient);
	}

	/**
	 * @description document内部api
	 * @author ouandyang
	 * @updateTime 2021/9/6
	 */
	public DocumentApi getDocumentApi(){
		return new DocumentApi(documentApiClient);
	}


	/**
	 * @description document内部api
	 * @author xiashenghui
	 * @updateTime 2022/7/7
	 */
	public AppstoreClient getAppstoreClient(){
		return new AppstoreClient(appstoreApiClient);
	}

	/**
	 * @description doc-share外部api
	 * @author yan.nan@aishu.cn
	 * @updateTime 2023/6/12
	 */
	public DocShareApi getDocShareApi(){
		return new DocShareApi(docsharePublicClient);
	}

	/**
	 * @description doc-share外部api
	 * @author yan.nan@aishu.cn
	 * @updateTime 2023/6/12
	 */
	public PersonalConfigApi getPersonalConfigApi(){
		return new PersonalConfigApi(personalConfigPrivateClient);
	}

	/**
	 * @description doc-share内部api
	 * @author siyu.chen
	 * @updateTime 2023/11/18
	 */
	public DocShareApi getDocSharePrivateApi(){
		return new DocShareApi(docsharePrivateClient);
	}
}
