// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/util"
	"gorm.io/gorm"
)

const TableNameTDwhAuthRequestForm = "t_dwh_auth_request_form"

// TDwhAuthRequestForm mapped from table <t_dwh_auth_request_form>
type TDwhAuthRequestForm struct {
	Sid              uint64    `gorm:"column:sid;type:bigint(20);primaryKey;comment:雪花ID" json:"sid"`                                                 // 雪花ID
	ID               string    `gorm:"column:id;type:char(36);not null;comment:申请单ID" json:"id"`                                                      // 申请单ID
	Name             string    `gorm:"column:name;type:varchar(255);not null;comment:申请单名称" json:"name"`                                              // 申请单名称
	Applicant        string    `gorm:"column:applicant;type:char(36);not null;comment:申请人（创建人）" json:"applicant"`                                     // 申请人（创建人）
	ApplyTime        int64     `gorm:"column:apply_time;type:bigint(20);not null;default:current_timestamp(3);comment:申请时间" json:"apply_time"`        // 申请时间
	DataID           string    `gorm:"column:data_id;type:char(36);not null;comment:数据ID，当前是库表的ID" json:"data_id"`                                    // 数据ID，当前是库表的ID
	DataTechName     string    `gorm:"column:data_tech_name;type:varchar(255);not null;comment:数据名称，当前是库表的技术名称" json:"data_tech_name"`                // 数据名称，当前是库表的技术名称
	DataBusinessName string    `gorm:"column:data_business_name;type:varchar(255);not null;comment:数据名称，当前是库表的业务名称" json:"data_business_name"`        // 数据名称，当前是库表的业务名称
	ApplyID          string    `gorm:"column:apply_id;type:varchar(64);comment:审核流程ID" json:"apply_id"`                                               // 审核流程ID
	ProcDefKey       string    `gorm:"column:proc_def_key;type:varchar(128);comment:审核流程key" json:"proc_def_key"`                                     // 审核流程key
	Phase            string    `gorm:"column:phase;type:varchar(64);not null;comment:权申请当前所处的阶段" json:"phase"`                                        // 权申请当前所处的阶段
	Message          string    `gorm:"column:message;type:text;not null;comment:策略请求处于当前阶段的原因" json:"message"`                                        // 策略请求处于当前阶段的原因
	CreatedAt        time.Time `gorm:"column:created_at;type:datetime(3);not null;default:current_timestamp(3);comment:创建时间, 申请时间" json:"created_at"` // 创建时间, 申请时间
	UpdatedAt        time.Time `gorm:"column:updated_at;type:datetime;not null;autoUpdateTime;comment:更新时间" json:"updated_at"`                        // 更新时间
	DeletedAt        int64     `gorm:"column:deleted_at;type:bigint(20);comment:删除时间(逻辑删除)" json:"deleted_at"`                                        // 删除时间(逻辑删除)
}

func (m *TDwhAuthRequestForm) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.Sid == 0 {
		m.Sid = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName TDwhAuthRequestForm's table name
func (*TDwhAuthRequestForm) TableName() string {
	return TableNameTDwhAuthRequestForm
}
