// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/util"
	"gorm.io/gorm"
)

const TableNameTDwhAuthRequestSpec = "t_dwh_auth_request_spec"

// TDwhAuthRequestSpec mapped from table <t_dwh_auth_request_spec>
type TDwhAuthRequestSpec struct {
	Sid              uint64 `gorm:"column:sid;type:bigint(20);primaryKey;comment:雪花ID" json:"sid"`                                          // 雪花ID
	ID               string `gorm:"column:id;type:char(36);not null;comment:子视图的ID" json:"id"`                                              // 子视图的ID
	Name             string `gorm:"column:name;type:varchar(255);not null;comment:子视图的名称" json:"name"`                                      // 子视图的名称
	RequestFormID    string `gorm:"column:request_form_id;type:char(36);not null;comment:申请单ID" json:"request_form_id"`                     // 申请单ID
	DraftSpec        string `gorm:"column:draft_spec;type:text;comment:申请行列的申请定义的草稿，以 JSON 序列化" json:"draft_spec"`                          // 申请行列的申请定义的草稿，以 JSON 序列化
	DraftExpiredAt   int64  `gorm:"column:draft_expired_at;type:bigint(20);comment:子视图的草稿过期时间" json:"draft_expired_at"`                     //子视图的草稿过期时间
	DraftRequestType string `gorm:"column:draft_request_type;type:varchar(32);not null;comment:申请类型，1数据核验，2数据查询" json:"draft_request_type"` // 草稿申请类型，1数据核验，2数据查询
	RequestType      string `gorm:"column:request_type;type:varchar(32);not null;comment:申请类型，1数据核验，2数据查询" json:"request_type"`             // 申请类型，1数据核验，2数据查询
	Spec             string `gorm:"column:spec;type:text;comment:申请行列的申请的定义，以 JSON 序列化" json:"spec"`                                        // 申请行列的申请的定义，以 JSON 序列化
	ExpiredAt        int64  `gorm:"column:expired_at;type:bigint(20);comment:子视图的过期时间" json:"expired_at"`                                   //子视图的过期时间
}

func (m *TDwhAuthRequestSpec) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.Sid == 0 {
		m.Sid = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName TDwhAuthRequestSpec's table name
func (*TDwhAuthRequestSpec) TableName() string {
	return TableNameTDwhAuthRequestSpec
}
