// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/util"
	"gorm.io/gorm"
)

const TableNameTTechnicalIndicator = "t_technical_indicator"

// TTechnicalIndicator mapped from table <t_technical_indicator>
type TTechnicalIndicator struct {
	ID                       uint64         `gorm:"column:id;comment:雪花id" json:"id"`                                                                       // 雪花id
	Name                     string         `gorm:"column:name;not null;comment:指标名称" json:"name"`                                                          // 指标名称
	Description              string         `gorm:"column:description;comment:指标名称描述" json:"description"`                                                   // 指标名称描述
	Code                     string         `gorm:"column:code;not null;comment:指标编号" json:"code"`                                                          // 指标编号
	IndicatorUnit            string         `gorm:"column:indicator_unit;not null;comment:指标单位" json:"indicator_unit"`                                      // 指标单位
	SubjectDomainID          string         `gorm:"column:subject_domain_id;comment:关联主题域id" json:"subject_domain_id"`                                      // 关联主题域id
	IndicatorType            string         `gorm:"column:indicator_type;not null;comment:指标类型:atomic原子derived衍生composite复合" json:"indicator_type"`         // 指标类型:atomic原子derived衍生composite复合
	DimensionModelID         int64          `gorm:"column:dimension_model_id;not null;comment:维度模型ID" json:"dimension_model_id"`                            // 维度模型ID
	Expression               string         `gorm:"column:expression;comment:指标表达式，如果指标是原子或复合指标时" json:"expression"`                                        // 指标表达式，如果指标是原子或复合指标时
	AtomicIndicatorID        uint64         `gorm:"column:atomic_indicator_id;comment:引用的原子指标，如果指标是衍生指标时" json:"atomic_indicator_id"`                       // 引用的原子指标，如果指标是衍生指标时
	TimeRestrict             string         `gorm:"column:time_restrict;comment:时间限定表达式，如果指标是衍生指标时" json:"time_restrict"`                                   // 时间限定表达式，如果指标是衍生指标时
	ModifierRestrict         string         `gorm:"column:modifier_restrict;comment:普通限定表达式，如果指标是衍生指标时" json:"modifier_restrict"`                           // 普通限定表达式，如果指标是衍生指标时
	ModifierRestrictRelation string         `gorm:"column:modifier_restrict_relation;default:AND;comment:普通限定表达式且或关系表达式" json:"modifier_restrict_relation"` // 普通限定表达式且或关系表达式
	BusinessIndicatorID      string         `gorm:"column:business_indicator_id;comment:业务指标ID" json:"business_indicator_id"`                               // 业务指标ID
	BusinessIndicatorName    string         `gorm:"column:business_indicator_name;comment:业务指标名称" json:"business_indicator_name"`                           // 业务指标名称
	ReferCount               uint32         `gorm:"column:refer_count;not null;comment:技术指标被引用的数量" json:"refer_count"`                                      // 技术指标被引用的数量
	UpdateCycle              string         `gorm:"column:update_cycle;comment:更新周期" json:"update_cycle"`                                                   // 更新周期
	OwnerUID                 string         `gorm:"column:owner_uid;comment:数据ownerID" json:"owner_uid"`                                                    // 数据ownerID
	OwnerName                string         `gorm:"column:owner_name;comment:数据owner名称" json:"owner_name"`                                                  // 数据owner名称
	MgntDepID                string         `gorm:"column:mgnt_dep_id;comment:职责部门ID" json:"mgnt_dep_id"`                                                   // 职责部门ID
	MgntDepName              string         `gorm:"column:mgnt_dep_name;comment:职责部门名称" json:"mgnt_dep_name"`                                               // 职责部门名称
	SceneAnalysisID          string         `gorm:"column:scene_analysis_id;comment:场景分析ID" json:"scene_analysis_id"`                                       // 场景分析ID
	AnalysisDimension        string         `gorm:"column:analysis_dimension;comment:分析维度" json:"analysis_dimension"`                                       // 分析维度
	Level                    string         `gorm:"column:level;comment:指标等级" json:"level"`                                                                 // 指标等级
	CreatedAt                time.Time      `gorm:"column:created_at;not null;default:current_timestamp(3);comment:创建时间" json:"created_at"`                 // 创建时间
	CreatorUID               string         `gorm:"column:creator_uid;comment:创建用户ID" json:"creator_uid"`                                                   // 创建用户ID
	CreatorName              string         `gorm:"column:creator_name;comment:创建用户名称" json:"creator_name"`                                                 // 创建用户名称
	UpdatedAt                time.Time      `gorm:"column:updated_at;not null;autoUpdateTime;comment:更新时间" json:"updated_at"`                               // 更新时间
	UpdaterUID               string         `gorm:"column:updater_uid;comment:更新用户ID" json:"updater_uid"`                                                   // 更新用户ID
	UpdaterName              string         `gorm:"column:updater_name;comment:更新用户名称" json:"updater_name"`                                                 // 更新用户名称
	DeletedAt                gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间(逻辑删除)" json:"deleted_at"`                                                 // 删除时间(逻辑删除)
	DeleterUID               string         `gorm:"column:deleter_uid;comment:删除用户ID" json:"deleter_uid"`                                                   // 删除用户ID
	DeleterName              string         `gorm:"column:deleter_name;comment:删除用户名称" json:"deleter_name"`                                                 // 删除用户名称
}

func (m *TTechnicalIndicator) BeforeCreate(_ *gorm.DB) error {
	if m == nil {
		return nil
	}

	if m.ID == 0 {
		m.ID = uint64(util.GetUniqueID())
	}

	return nil
}

// TableName TTechnicalIndicator's table name
func (*TTechnicalIndicator) TableName() string {
	return TableNameTTechnicalIndicator
}
