// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice (interfaces: DocAuditRESTRepo,RawDocAuditRESTRepo)
//
// Generated by this command:
//
//	mockgen -destination=doc_audit_rest.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice DocAuditRESTRepo,RawDocAuditRESTRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/dto"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=doc_audit_rest.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice DocAuditRESTRepo,RawDocAuditRESTRepo

// MockDocAuditRESTRepo is a mock of DocAuditRESTRepo interface.
type MockDocAuditRESTRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDocAuditRESTRepoMockRecorder
	isgomock struct{}
}

// MockDocAuditRESTRepoMockRecorder is the mock recorder for MockDocAuditRESTRepo.
type MockDocAuditRESTRepoMockRecorder struct {
	mock *MockDocAuditRESTRepo
}

// NewMockDocAuditRESTRepo creates a new mock instance.
func NewMockDocAuditRESTRepo(ctrl *gomock.Controller) *MockDocAuditRESTRepo {
	mock := &MockDocAuditRESTRepo{ctrl: ctrl}
	mock.recorder = &MockDocAuditRESTRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDocAuditRESTRepo) EXPECT() *MockDocAuditRESTRepoMockRecorder {
	return m.recorder
}

// GetDocAuditByBizID mocks base method.
func (m *MockDocAuditRESTRepo) GetDocAuditByBizID(ctx context.Context, bizID string) (*dto.DocAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocAuditByBizID", ctx, bizID)
	ret0, _ := ret[0].(*dto.DocAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocAuditByBizID indicates an expected call of GetDocAuditByBizID.
func (mr *MockDocAuditRESTRepoMockRecorder) GetDocAuditByBizID(ctx, bizID any) *MockDocAuditRESTRepoGetDocAuditByBizIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocAuditByBizID", reflect.TypeOf((*MockDocAuditRESTRepo)(nil).GetDocAuditByBizID), ctx, bizID)
	return &MockDocAuditRESTRepoGetDocAuditByBizIDCall{Call: call}
}

// MockDocAuditRESTRepoGetDocAuditByBizIDCall wrap *gomock.Call
type MockDocAuditRESTRepoGetDocAuditByBizIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocAuditRESTRepoGetDocAuditByBizIDCall) Return(arg0 *dto.DocAudit, arg1 error) *MockDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocAuditRESTRepoGetDocAuditByBizIDCall) Do(f func(context.Context, string) (*dto.DocAudit, error)) *MockDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocAuditRESTRepoGetDocAuditByBizIDCall) DoAndReturn(f func(context.Context, string) (*dto.DocAudit, error)) *MockDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsAuditor mocks base method.
func (m *MockDocAuditRESTRepo) IsAuditor(ctx context.Context, bizID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuditor", ctx, bizID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAuditor indicates an expected call of IsAuditor.
func (mr *MockDocAuditRESTRepoMockRecorder) IsAuditor(ctx, bizID any) *MockDocAuditRESTRepoIsAuditorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuditor", reflect.TypeOf((*MockDocAuditRESTRepo)(nil).IsAuditor), ctx, bizID)
	return &MockDocAuditRESTRepoIsAuditorCall{Call: call}
}

// MockDocAuditRESTRepoIsAuditorCall wrap *gomock.Call
type MockDocAuditRESTRepoIsAuditorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDocAuditRESTRepoIsAuditorCall) Return(arg0 bool, arg1 error) *MockDocAuditRESTRepoIsAuditorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDocAuditRESTRepoIsAuditorCall) Do(f func(context.Context, string) (bool, error)) *MockDocAuditRESTRepoIsAuditorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDocAuditRESTRepoIsAuditorCall) DoAndReturn(f func(context.Context, string) (bool, error)) *MockDocAuditRESTRepoIsAuditorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRawDocAuditRESTRepo is a mock of RawDocAuditRESTRepo interface.
type MockRawDocAuditRESTRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRawDocAuditRESTRepoMockRecorder
	isgomock struct{}
}

// MockRawDocAuditRESTRepoMockRecorder is the mock recorder for MockRawDocAuditRESTRepo.
type MockRawDocAuditRESTRepoMockRecorder struct {
	mock *MockRawDocAuditRESTRepo
}

// NewMockRawDocAuditRESTRepo creates a new mock instance.
func NewMockRawDocAuditRESTRepo(ctrl *gomock.Controller) *MockRawDocAuditRESTRepo {
	mock := &MockRawDocAuditRESTRepo{ctrl: ctrl}
	mock.recorder = &MockRawDocAuditRESTRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawDocAuditRESTRepo) EXPECT() *MockRawDocAuditRESTRepoMockRecorder {
	return m.recorder
}

// GetDocAuditByBizID mocks base method.
func (m *MockRawDocAuditRESTRepo) GetDocAuditByBizID(ctx context.Context, bizID string) (*dto.DocAudit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocAuditByBizID", ctx, bizID)
	ret0, _ := ret[0].(*dto.DocAudit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocAuditByBizID indicates an expected call of GetDocAuditByBizID.
func (mr *MockRawDocAuditRESTRepoMockRecorder) GetDocAuditByBizID(ctx, bizID any) *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocAuditByBizID", reflect.TypeOf((*MockRawDocAuditRESTRepo)(nil).GetDocAuditByBizID), ctx, bizID)
	return &MockRawDocAuditRESTRepoGetDocAuditByBizIDCall{Call: call}
}

// MockRawDocAuditRESTRepoGetDocAuditByBizIDCall wrap *gomock.Call
type MockRawDocAuditRESTRepoGetDocAuditByBizIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall) Return(arg0 *dto.DocAudit, arg1 error) *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall) Do(f func(context.Context, string) (*dto.DocAudit, error)) *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall) DoAndReturn(f func(context.Context, string) (*dto.DocAudit, error)) *MockRawDocAuditRESTRepoGetDocAuditByBizIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
