// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice (interfaces: VirtualizationEngineRepo)
//
// Generated by this command:
//
//	mockgen -destination=virtualization_engine.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice VirtualizationEngineRepo
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/dto"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -destination=virtualization_engine.go -package=mock -typed -write_generate_directive github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/microservice VirtualizationEngineRepo

// MockVirtualizationEngineRepo is a mock of VirtualizationEngineRepo interface.
type MockVirtualizationEngineRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualizationEngineRepoMockRecorder
	isgomock struct{}
}

// MockVirtualizationEngineRepoMockRecorder is the mock recorder for MockVirtualizationEngineRepo.
type MockVirtualizationEngineRepoMockRecorder struct {
	mock *MockVirtualizationEngineRepo
}

// NewMockVirtualizationEngineRepo creates a new mock instance.
func NewMockVirtualizationEngineRepo(ctrl *gomock.Controller) *MockVirtualizationEngineRepo {
	mock := &MockVirtualizationEngineRepo{ctrl: ctrl}
	mock.recorder = &MockVirtualizationEngineRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualizationEngineRepo) EXPECT() *MockVirtualizationEngineRepoMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockVirtualizationEngineRepo) Fetch(ctx context.Context, sql string) (*dto.VirtualizationEngineViewData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, sql)
	ret0, _ := ret[0].(*dto.VirtualizationEngineViewData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockVirtualizationEngineRepoMockRecorder) Fetch(ctx, sql any) *MockVirtualizationEngineRepoFetchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockVirtualizationEngineRepo)(nil).Fetch), ctx, sql)
	return &MockVirtualizationEngineRepoFetchCall{Call: call}
}

// MockVirtualizationEngineRepoFetchCall wrap *gomock.Call
type MockVirtualizationEngineRepoFetchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVirtualizationEngineRepoFetchCall) Return(arg0 *dto.VirtualizationEngineViewData, arg1 error) *MockVirtualizationEngineRepoFetchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVirtualizationEngineRepoFetchCall) Do(f func(context.Context, string) (*dto.VirtualizationEngineViewData, error)) *MockVirtualizationEngineRepoFetchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVirtualizationEngineRepoFetchCall) DoAndReturn(f func(context.Context, string) (*dto.VirtualizationEngineViewData, error)) *MockVirtualizationEngineRepoFetchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
