// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/kweaver-ai/idrm-go-common/audit"
	v1_2 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	"github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl3 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl9 "github.com/kweaver-ai/idrm-go-common/rest/automation/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl4 "github.com/kweaver-ai/idrm-go-common/rest/data_application_service/impl"
	impl8 "github.com/kweaver-ai/idrm-go-common/rest/data_model/impl"
	impl5 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	impl6 "github.com/kweaver-ai/idrm-go-common/rest/indicator_management/impl"
	impl11 "github.com/kweaver-ai/idrm-go-common/rest/studio_web/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/user_management"
	"github.com/kweaver-ai/idrm-go-common/trace"
	"github.com/kweaver-ai/idrm-go-frame"
	"github.com/kweaver-ai/idrm-go-frame/core/transport/rest"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/database"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/gorm"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/resources"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driver"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driver/v2/auth"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driver/v2/data_auth"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/settings"
	impl7 "github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/domain/common_auth/impl"
	impl10 "github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/domain/data_auth/impl"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/infrastructure/repository/db"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/infrastructure/repository/redis"
)

// Injectors from wire.go:

func InitApp(s *settings.Settings) (*AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := impl.NewHydraByService(client)
	drivenUserMgnt := user_management.NewUserMgntByService(client)
	driven := impl2.NewConfigurationCenterDrivenByService(client)
	logger := audit.Discard()
	authorizationDriven := impl3.NewDriven(client)
	authServiceInternalV1Interface, err := v1.NewInternalForBase(client)
	if err != nil {
		return nil, nil, err
	}
	middleware := v1_2.NewMiddleware(hydra, drivenUserMgnt, driven, logger, authorizationDriven, authServiceInternalV1Interface)
	redisClient := redis.NewRedisClient()
	gormDB, err := db.NewMariaDB(s)
	if err != nil {
		return nil, nil, err
	}
	indicatorDimensionalRuleInterface := gorm.NewIndicatorDimensionalRuleInterfaceRepository(gormDB)
	data_application_serviceDriven := impl4.NewDrivenImpl(client)
	data_viewDriven := impl5.NewDataViewDriven(client)
	indicator_managementDriven := impl6.NewDrivenImpl(client)
	gormDBWithoutDatabase, err := db.NewGormDBWithoutDatabase(s)
	if err != nil {
		return nil, nil, err
	}
	databaseClient := database.New(gormDBWithoutDatabase)
	common_authAuth := impl7.NewAuth(authorizationDriven, redisClient, indicatorDimensionalRuleInterface, driven, data_application_serviceDriven, data_viewDriven, indicator_managementDriven, databaseClient, drivenUserMgnt)
	controller := auth.NewController(common_authAuth)
	data_modelDriven := impl8.NewDrivenImpl(client)
	automationDriven := impl9.NewDriven(client)
	useCase := impl10.NewDataAuth(data_modelDriven, automationDriven)
	data_authController := data_auth.NewController(useCase)
	router := &driver.Router{
		Middleware:       middleware,
		AuthV2Controller: controller,
		DataAuthV2:       data_authController,
	}
	server := driver.NewHttpServer(s, router)
	app := newApp(server)
	studio_webDriven := impl11.NewDriven(client)
	registerClient := resources.NewRegisterClient(authorizationDriven, studio_webDriven)
	appRunner := &AppRunner{
		App:              app,
		resourceRegister: registerClient,
	}
	return appRunner, func() {
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))

func newApp(hs *rest.Server) *idrm_go_frame.App {
	return idrm_go_frame.New(idrm_go_frame.Name(Name), idrm_go_frame.Server(hs))
}
